### ISSUE TITLE
Research App Security best practices

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#101]
Possible practices
- Server certificate verification

**Comment by jonasanker** [comment]
@HeeysamH You had one specific thing in mind when you joined the team. What was that?

**Comment by marfavi** [comment]
We might want to discuss this ahead of the autumn semester start

This discussion is possibly blocking related issue #169

**Comment by fremartini** [comment]
@jonasanker what did you have in mind regarding this issue?  @TTA777 and i discussed this and we don't see any noticeable improvements that could be made. I suggest we close this

**Comment by jonasanker** [comment]
@fremartini @TTA777 I think this issue was a spin-off from a team member arguing that the app was vulnerable to Man in middle attacks. Therefore this issue was raised to have general awareness on security on to verify compliance according to best practices.

**Comment by TTA777** [comment]
Hmm, so it appears there is a practice known as [SSL pinning](https://owasp.org/www-community/controls/Certificate_and_Public_Key_Pinning) where the client verifies the server is using the expected certificate. Seems that you can either check the certificate itself, or the public key in it is the expected one.

Verifying the certificate itself introduces the issue of having to update the app every time the server receives a new certificate. I am unsure whether we would have the same issue for the public key of the certificate if we used that for verification

**Comment by jonasanker** [comment]
I had the same thoughts and concerns @TTA777 . Currently I would argue that certificate pinning is not worth it and would likely just pose a risk that the app would break sometime in the future because we forgot to update the certificate 😅
