### ISSUE TITLE
Rename app to "Analog"

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#111]
Since the app name can be different on the app store and home screen, I want to propose renaming the app:
* Home screen (app drawer): ~Cafe Analog~ → **Analog**
* App stores: **Cafe Analog** _(unchanged)_

This way it is still easy to find on the App store, but once you have it installed, the app name won't overflow.

Will solve related issue #35

**Comment by jonasanker** [comment]
I'm fine with this change. Let's go 🎉
