### ISSUE TITLE
`FilterBar` should be able to display two dropdowns

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#148]
Take a look on this filter bar in the design spec:
![image](https://user-images.githubusercontent.com/21163286/154137453-223b6db5-3ae5-4673-92fb-b5bd65cde502.png)

**Comment by jonasanker** [comment]
@jonasanker Link to backend story

**Comment by fremartini** [comment]
@marfavi what should the options be?
* Programmes (student avg)
* ... ?

**Comment by marfavi** [comment]
Timeframe:
- This month (default)
- This semester
- All time

Show:
- Everyone (default)
- Programmes by average
- ???

Idea should be fleshed out & implemented in backend before proceeding

**Comment by marfavi** [comment]
Not part of the v4 design specification. Idea not well fleshed out. Closing
