### ISSUE TITLE
Ensure responsiveness

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#151]
Some views are overflowing vertically on small devices. We need to ensure that all the views in question can be scrolled to prevent this.

Using `lib/utils/responsive.dart`, we can check if the device used is small/narrow (<= 325 [dp](https://en.wikipedia.org/wiki/Device-independent_pixel) wide).

- [x] #178
- [x] #230

**Comment by fremartini** [comment]
would wrapping the body of every page in a listview thereby making it scrollable if the screen is not large enough, solve the problem?

**Comment by marfavi** [comment]
> would wrapping the body of every page in a listview thereby making it scrollable if the screen is not large enough, solve the problem? 

The fix should be considered on a page by page basis
