### ISSUE TITLE
Add environment warning on receipt-popup

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#158]

**Comment by fremartini** [comment]
so when should this be displayed? As it stands, the 'Connected to test environment' banner is already shown when inspecting a receipt:

![image](https://user-images.githubusercontent.com/39860858/155171256-d96f1ba9-a7ab-4915-8877-9cef7a7d2514.png)

**Comment by Jens-Fastrup** [comment]
Is it clear enough though? Like, would a barista notice if a customer used the test version of the app for espresso purchase? :)

**Comment by fremartini** [comment]
@Jens-Fastrup did you have a look at this? I personally think the already implemented solution is sufficient. @jonasanker @marfavi @TTA777 thoughts?

**Comment by jonasanker** [comment]
@fremartini I think I had the idea of a visually more clear indication of that the ticket is not valid (bc test environment). It does need to look fancy. It could just be a text in a powerful color

**Comment by Jens-Fastrup** [comment]
yes, as Jonas says just maybe add a red or yellow background to the ticket if the environment is set to test

**Comment by marfavi** [comment]
I will look at it today

**Comment by Jens-Fastrup** [comment]
Cool in any case, I've figured to change the receipt color based on the environment which could be an option. Will push up on branch soon
