### ISSUE TITLE
login textfield autocorrects input on iOS

### ISSUE THREAD

**Issue by TikoyX** [AnalogIO/coffeecard_app#161]
When entering an email in the sign in textfield, the text is autocorrected thus sometimes editing the input to a wrong email.

**Comment by marfavi** [comment]
Check if it is still the case (might have been a flutter issue that has been fixed, none of the testers have reported this one)

**Comment by marfavi** [comment]
No longer an issue, presumably fixed by Flutter.

In login flow, no input suggestions are given
In register flow, suggests text but does not autocorrect.
