### ISSUE TITLE
Allow user to set itself as Anonymous

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#162]
A user should be able to mark himself to be anonymous on the leaderboards. This is already implemented in the existing apps.
Setting should be added to Account Settings.

**Comment by jonasanker** [comment]
@marfavi Do you have any design considerations we should consider for this one?

**Comment by marfavi** [comment]
Should be added here as a fourth setting 
![image](https://user-images.githubusercontent.com/21163286/154906045-cdf43921-7675-48e8-9f89-e212ce63a40a.png)

**Comment by fremartini** [comment]
would be nice to have closed #119  before i start this

**Comment by fremartini** [comment]
what do you think the text should say?
* Be anonymous on the leaderboard
* Show me on the leaderboard
* Display me on the leaderboard
something else?

**Comment by Jens-Fastrup** [comment]
Måske "Join leaderboard"?
