### ISSUE TITLE
Receipt displays wrong time

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#183]
Swipe happened at 17:27
![image](https://user-images.githubusercontent.com/39860858/157709013-1b7bc10b-c4c1-4982-86f0-537cf02110d9.png)

**Comment by TTA777** [comment]
If I remember correctly, time in the backend is UTC, as it should be, but we do no mapping in the app to go from UTC to CEST,  which would explain the time difference

**Comment by jonasanker** [comment]
Thomas is right. The date format is in UTC

Example
```
2022-01-09T21:03:52.2283208Z
```
