### ISSUE TITLE
Allow user to update their programme

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#187]

**Comment by jonasanker** [comment]
Good finding. This is currently not possible and we actually considered this a P1 as it is not possible in the current app anyway

**Comment by fremartini** [comment]
> Good finding. This is currently not possible and we actually considered this a P1 as it is not possible in the current app anyway

Right... i think me may want to push the whole programme thing to P1 then. Dosent make sense to be assigned a programme and not be able to update it

**Comment by jonasanker** [comment]
I agree ✅
