### ISSUE TITLE
User should be able to change their email

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#207]

**Comment by fremartini** [comment]
@jonasanker @TTA777 what endpoint is used to update the email? is it update account? I assume we also need to send a verification email here. How to handle?

**Comment by jonasanker** [comment]
@fremartini it's the same endpoint used for updating all properties of a user. The backend only updates the properties which are provided, those who shouldn't be updated, should be left out.

https://api-test.analogio.dk/coffeecard/swagger/index.html?urls.primaryName=v1#/Account/Account_Update

I cannot recall if we send a verify email in the backend but that should not be the concern of the app
