### ISSUE TITLE
Create error page

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#208]
Many places in the codebase we display no errors when a page cannot be loaded:
```dart
//FIXME: display error
return const Text('error');
```

We need to develop a page that can let the user know that an error has occured

**Comment by TTA777** [comment]
Another idea could be to have a stream we could send all errors to, which would then trigger a pop-up in the app whenever it received an error. This is just an idea, so obviously not thought out that well, but should be doable, and wouldn't interrupt the user experience as much as being redirected to a new page
