### ISSUE TITLE
`CardBase` should not be a class to be inherited

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#212]
Currently it stops us from doing some specific things with some cards (no access to a `BuildContext` and therefore no responsive features on the card's properties)
Use of composition should be utilized instead.

**Comment by fremartini** [comment]
what do you suggest we do instead? flutter also provides the 'mixin' classes, perhaps they could be useful

**Comment by marfavi** [comment]
> what do you suggest we do instead? flutter also provides the 'mixin' classes, perhaps they could be useful

Just make it a normal widget that can be used by other widgets. E.g. the build method in ReceiptCard would return CardBase with the appropriate properties and styling
