### ISSUE TITLE
(Fix workaround) Leaderboard doesn't get updated after user information updates

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#248]
Your entry in the leaderboards will be not be hightlighted after changing your name in Settings

**Comment by marfavi** [comment]
A proper implementation is blocked by a bug in the API

**Comment by jonasanker** [comment]
@marfavi Is it the bug for the PUT request which is blocking this?

**Comment by marfavi** [comment]
> @marfavi Is it the bug for the PUT request which is blocking this?

Yes

**Comment by marfavi** [comment]
#255 fixes this with a small workaround, issue should be left open until workaround is removed

**Comment by marfavi** [comment]
The PUT users request returns a User object with all ranks (month, semester, all time) set to 0. We fix this by requesting the GET User endpoint that will return the correct values.

We want to fix the PUT endpoint, so it returns the correct values
