### ISSUE TITLE
Setup Firebase

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#25]
- Firebase Crashlytics
- Firebase Performance
- Firebase Analytics

**Comment by jonasanker** [comment]
A new Firebase project for iOS should also be created in Firebase Console

**Comment by marfavi** [comment]
@jonasanker what's the status of this?

Is it prioritized correctly? [For reference, take a look at the other (unlocked) P1 issues.](https://github.com/AnalogIO/coffeecard_app/issues?q=is%3Aopen+label%3AP1+-label%3Ablocked)

**Comment by jonasanker** [comment]
@marfavi 
No status but might be able to solve the 
task in this weekend. I think P1/P0 is fitting as Firebase integration allows us to catch stack traces in case of errors etc
