### ISSUE TITLE
Two leaderboard entries with the same number of swipes get tie-broken arbitrarily

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#250]
Should be tied instead of broken based off some arbitrary condition

Likely an analog-core issue

**Comment by fremartini** [comment]
what should the correct behaviour be? if two people have the same score, should they have the same position? should we go by alphabetical order?

**Comment by marfavi** [comment]
> what should the correct behaviour be? if two people have the same score, should they have the same position? should we go by alphabetical order?

They should share the same rank, whoever comes first in the list is not important.

If multiple people people share a top ten spot place, we should display more than 10 people in that list so everyone with rank ≤ 10 shows up

**Comment by marfavi** [comment]
Consider this scenario:
![image](https://user-images.githubusercontent.com/21163286/167647421-f7110594-c279-4396-b81d-09c5142f44b1.png)

In this case, "omid test" (the account I'm logged into) should be tied with "mmmmm..." at 8th place, but according to "Your stats" i'm ranked 9th
![image](https://user-images.githubusercontent.com/21163286/167647649-0e512bbb-9576-4600-813b-7114acbc924c.png)

This value is returned by the backend. It should return 8th instead of 9th.
Meaning this is a backend issue.
Do you agree @TTA777 ?

**Comment by marfavi** [comment]
No issue -- ties are sorted by last swipe date
