### ISSUE TITLE
Programme page overflows

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#288]
![Screenshot_20220511-222231.jpg](https://user-images.githubusercontent.com/39860858/167941217-a1441788-b33d-4232-9a2e-c19bb854dd14.jpg)

**Comment by fremartini** [comment]
@marfavi this seems to be a problem caused by ListEntrySide as the text does not overflow but pushes the radio button outside the screen. I think a possible solution could be to swap the radiobutton and the text, what do you think? Otherwise we may need to introduce a ListEntrySide.None option that wouldn't expand any of the sides

**Comment by marfavi** [comment]
> @marfavi this seems to be a problem caused by ListEntrySide as the text does not overflow but pushes the radio button outside the screen. I think a possible solution could be to swap the radiobutton and the text, what do you think? Otherwise we may need to introduce a ListEntrySide.None option that wouldn't expand any of the sides

Just need to change the side to expand. SettingListEntry has that set to left, when it should be right for the list entries here

**Comment by marfavi** [comment]
Added two PRs that fix the issue because I came up with a better solution after the first PR.

Feel free to merge either one
