### ISSUE TITLE
Add shortname

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#35]
Currently the app only has the name 'Cafe Analog'. It needs a 'shortname'

**Comment by jonasanker** [comment]
![Screenshot_20220108-170501~2.jpg](https://user-images.githubusercontent.com/25930103/148651219-975a50da-13c0-4538-9e64-5294fc37e9d1.jpg)

**Comment by marfavi** [comment]
Not possible it seems, my bad

**Comment by marfavi** [comment]
Unless we want to rename the app to 'Analog', but that should be a discussion of its own

**Comment by jonasanker** [comment]
Thanks for investigating. I think it's fine for now unless we just call it `Analog` which I think would be just fine
