### ISSUE TITLE
Handle errors occurring while using a ticket

### ISSUE THREAD

**Issue by TTA777** [AnalogIO/coffeecard_app#362]
While the TicketsCubit does emit error states, the TicketsSections listening on it does not react to these. The result is if an error occurs while swiping a ticket, the user will be trapped on a loading spinner. 

How to reproduce:
1. Open the app to the homescreen
2. Turn off internet on the device
3. Swipe a ticket
4. Be trapped on a loading spinner since the error state is not handled

**Comment by marfavi** [comment]
This is a repository level bug. API calls can throw an exception (eg when the client is offline), which should be caught by the repository, so it can properly return a Left.

See how we fixed this issue in `AppConfigRepository`:
```dart
  Future<Either<ApiError, Environment>> getEnvironmentType() async {
    final Response<AppConfig> response;
    try {
      response = await _api.apiV2AppconfigGet();
    } catch (e) {
      return const Left(ApiError("Couldn't connect to the server"));
    }
```

I will fix it

**Comment by TTA777** [comment]
While that might contribute to the problem, part of it is likely also that the block listener in TicketSection does not react to the error state, hence the loading overlay is never removed.

Snippet of the block listener
`        BlocConsumer<TicketsCubit, TicketsState>(
          listener: (context, state) {
            if (state is TicketUsing) {
              if (Navigator.of(context, rootNavigator: true).canPop()) {
                // If a ticket was used from the puy
                // single drink flow, there is no swipe overlay

                // Remove the swipe overlay
                Navigator.of(context, rootNavigator: true).pop();
              }
              // TODO: consider using a nicer loading indicator
              showLoadingOverlay(context);
            } else if (state is TicketUsed) {
              // Refresh or load user info (for updated rank stats)
              // (also refreshes leaderboard)
              context.read<UserCubit>().fetchUserDetails();

              final envState = context.read<EnvironmentCubit>().state;
              hideLoadingOverlay(context);
              ReceiptOverlay.of(context).show(
                receipt: state.receipt,
                isTestEnvironment:
                    envState is EnvironmentLoaded && envState.env.isTest,
              );
            }
          },
`
