### ISSUE TITLE
When shiftplanning endpoint returns 404, opening hours is greyed out in Settings

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#391]
![IMG_3301](https://user-images.githubusercontent.com/21163286/208739504-195d6493-3a0e-48fd-855c-ee84f6bd9e5c.PNG)

**Comment by jonasanker** [comment]
@marfavi Can you create an issue on Shiftplanning API repo for what would be a better response?

I would argue either 402 No content or an empty array
