### ISSUE TITLE
Barista hub 

### ISSUE THREAD

**Issue by fredpetersen** [AnalogIO/coffeecard_app#412]
Baristas should have a separate page for their perks.
This page should:
* Allow them to claim free on-shift drink
* Allow them to claim free filter/tea always
* Buy discounted off-shift drinks
* swipe barista drinks

Design by Omid:
![image](https://user-images.githubusercontent.com/43568735/228289705-c5ab54f4-dafa-47d2-b057-432c40e32a03.png)
Left design has perks together, second design uses sections

**Comment by fremartini** [comment]
closed by #413
