### ISSUE TITLE
Find a permanent solution to getting barista products

### ISSUE THREAD

**Issue by fredpetersen** [AnalogIO/coffeecard_app#422]
As per the barista hub change, the barista products are hardcoded in the app in `/lib/data/repositories/barista_product/barista_product_repository.dart`

These should be fetched from the backend, after we have marked barista products in the database

**Comment by marfavi** [comment]
Awaiting a backend change

**Comment by jonasanker** [comment]
@marfavi What are your requirements for the app? Would grouping a product category enum suffice?

**Comment by marfavi** [comment]
How about a list of user groups?

´´´
enum UserGroup { customer, barista, ... };

// field in product replacing the isVisible boolean
List<UserGroup> visibleTo;
´´´
