### ISSUE TITLE
Avoid type casting 204 return types from API

### ISSUE THREAD

**Issue by marfavi** [AnalogIO/coffeecard_app#426]
PR #424 addressed an issue where the backend returns a Null type when the call is 204 (No Content). Our generated client doesn't take this into account (it assumes a successful request always returns the specified type). Therefore, the solution by the mentioned PR casts the return type into a nullable version of the expected return type.

A lot of our endpoints can potentially return 204, which means that our generated client could still potentially fail in cases not covered by #424. Therefore, we should fix the relevant issue https://github.com/AnalogIO/analog-core/issues/148, then revert the changes made by the PR #424.

**Comment by jonasanker** [comment]
No longer blocked, was solved in https://github.com/AnalogIO/analog-core/issues/148
