### ISSUE TITLE
MobilePay support

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#43]
Create support for MobilePay in Flutter

Tasks:
- Create an abstract class for making a MobilePay payment

Implement class
- [x] #44
- [x] #45 

Relevant documentation [MobilePay Dev: Build on Mobile](https://mobilepaydev.github.io/MobilePay-Payments-API/docs/guides/app-payments/build-on-mobile)

Link to backend issue https://github.com/AnalogIO/analog-core/issues/31

**Comment by jonasanker** [comment]
@fremartini Having two eyes on this could be great. Do you want to join?

**Comment by fremartini** [comment]
> @fremartini Having two eyes on this could be great. Do you want to join?

yes, lets do it
