### ISSUE TITLE
Receipts page is not updated when swiping a ticket

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#448]
When a user swipes a ticket, the Receipts page is not updated. This gives a bad user experience when a user has swiped a ticket and then opens the Receipts page, the recently swiped ticket will not show unless a user makes a pull-down gesture to manually refresh Receipts.

## How to reproduce

1. Swipe a ticket
2. Go to the Receipts page. The just-swiped ticket is not shown

## Notes
When making a purchase or buying a single drink, the Receipts page seems to be refreshed automatically. So likely this functionality should be implemented for Swiped tickets too.

**Comment by marfavi** [comment]
Receipts should be updated when swiping a ticket or completing a purchase

**Comment by jonasanker** [comment]
@marfavi I have updated the description to be more accurate. This is an issue for swiped tickets. For Purchases, it works as expected
