### ISSUE TITLE
'Hero Widget' Exception is thrown when using ticket

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#466]
When using a ticket, the Hero widget causes an exception to be thrown:

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.
Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
have a unique non-null tag.
In this case, multiple heroes had the following tag: 1
├# Here is the subtree for one of the offending heroes: Hero

**Comment by marfavi** [comment]
Works on my machine. Are you using Flutter 3.10.0?

Try showing the output of running `flutter doctor`.
