### ISSUE TITLE
Show if app is using test environment

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#57]
Find a way to clearly highlight if app is connected to the testing environment backend.

Calling [GET api/v1/AppConfig](https://analogio.dk/clippy/swagger/index.html#/AppConfig/AppConfig_Get) returns the environment status.

**Comment by fremartini** [comment]
Proposal: use the 'Debug' banner as a way to indicate that the app is using the test environment
![image](https://user-images.githubusercontent.com/39860858/149619697-3d08b33b-3990-4f27-8576-f0bd1b2d16d2.png)

This can be enabled using the 'debugShowCheckedModeBanner' field in 'MaterialApp' in main.dart

**Comment by marfavi** [comment]
> Proposal: use the 'Debug' banner as a way to indicate that the app is using the test environment

Hijacking the debug banner means that a developer won't be able to distinguish between the app running in debug or profile mode. I think we should make our own widget to be more explicit than this.

My proposal looks something like this. A persistent widget that will get shown on top of any screen and would not capture any tap events. This solution wraps the outermost widget (MaterialApp/BlocProvider) in a Stack.

![Untitled-1](https://user-images.githubusercontent.com/21163286/149831327-c0d14781-f9cb-448a-bfa6-91ddbb849b0c.png)

**Comment by jonasanker** [comment]
@marfavi That's a good point, Omid. 

I would also like to add that one motivation for making the environment visible (for test environments only) is also to communicate to baristas that e.g. a purchase or a swiped ticket is not valid. With that in mind, I think it would be great if we visually can make it very clear when the app is connected to a test environment.
