### ISSUE TITLE
Check if current bearer token is expired

### ISSUE THREAD

**Issue by TTA777** [AnalogIO/coffeecard_app#68]
Currently, we don't check if the bearer token is expired, which results in the user appearing logged in, but the requests fail.

Two potential solutions could be to either:
- Check in the AuthBloc whether the retrieved token is valid, and has a reasonable time left to be used in
- Check in the authentication interceptor if the token is valid on requests

Another question is, what behaviour do we want when we see an expired token, i.e. do we want to either:
- Kick the user back to the login screen?
- Use stored user credentials to get a new bearer token from the API?

**Comment by jonasanker** [comment]
The Chopper library we're using as Http client, supports an authentication challenge class. 

The documentation is a little sparse. My understanding is that in the case a request Http fails with a Http 401 request, the authenticator class can be implemented to e.g. retry a request, call an API to get a new token etc.

References
- [Authenticator class](https://pub.dev/documentation/chopper/latest/chopper/Authenticator-class.html)
- [Flutter Chopper 401 renew & retry interceptor](https://stackoverflow.com/questions/67021327/flutter-chopper-401-renew-retry-interceptor)
