### ISSUE TITLE
PaymentDetails throws JsonUnsupportedObjectError

### ISSUE THREAD

**Issue by fremartini** [AnalogIO/coffeecard_app#70]
JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'InitatePurchaseRequest') thrown by coffeecard_api_v2.swagger.swagger.chopper.dart

![image](https://user-images.githubusercontent.com/39860858/150522286-df7bd94b-21e5-4f36-a3a2-26ebefc06e59.png)

**Comment by jonasanker** [comment]
Bug report created https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/335

**Comment by jonasanker** [comment]
Relates to #103

**Comment by TTA777** [comment]
The generated code offers custom methods that serve this purpose that we need to make use of for enums. In this instance, we use paymentTypeToJson() to solve it.
