### ISSUE TITLE
Develop app release pipeline to Firebase App Distribution for iOS

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/coffeecard_app#97]
Similar to the Android release pipeline on `develop` branches, the iOS app should be built and shared to Firebase App Distribution

Possible guides for a solution:
- [Distribute iOS apps to testers using the Firebase console](https://firebase.google.com/docs/app-distribution/ios/distribute-console?authuser=0)
- [How to build and sign your Flutter iOS application using GitHub Actions](https://damienaicheh.github.io/flutter/github/actions/2021/04/22/build-sign-flutter-ios-github-actions-en.html)

**Comment by jonasanker** [comment]
@HeeysamH Is this a ticket you want to look into? Since you're on Macbook :)

**Comment by fremartini** [comment]
@jonasanker how is it going with this one? should we look at it together next time?
